### PR TITLE
Add primary_currency to user object

### PR DESCRIPTION
**Pull request by SaalikLok**
Hi @mmenanno! This client library is so wonderful to work with. Thanks for writing it!

When I was using it today, I couldn't get the `User` object via `api.me`. Looks like it's because of a change in the LunchMoney API. A `primary_currency` field was added to the User, and the gem didn't know how to handle it.

The error I got
image

Response from LunchMoney API
image

This PR adds `primary_currency` to the `User` object. Tested from my forked version of the repo. Let me know if this PR needs anything else!

### CODE REVIEW

**Comment by mmenanno** [comment]
Thanks for this! Code looks good initially, but let me figure out why the unit tests aren't running on your PR 👀

**Review by mmenanno — APPROVED** [review]
Thanks for this!

**Comment by mmenanno** [comment]
@SaalikLok I've bumped the gem version v1.3.0 should have your change

**Comment by SaalikLok** [comment]
@mmenanno Thanks! 🙌

**Pull request merged**
